
name: Node.js CI

on:
  workflow_dispatch:
   
jobs:
  run-cypress-tests:
    runs-on: ubuntu-latest
    steps:
     #- name: Setup and run Cypress
    - name: install deps
      uses: cypress-io/github-action@v2
    - uses: actions/checkout@v2
      with:
          browser: chrome
          headless: true
          start: npm start
    
   
