name: testing
on: 
  workflow_dispatch:
  

jobs:
  install_deps:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: npm install
      - run: npm start

