
name: Node.js CI

on:
  workflow_dispatch:
   
jobs:
  run-cypress-tests:
  
    runs-on: ubuntu-latest
    defaults:
          run:
            shell: bash
            working-directory: ./frontend
    steps:
    - name: install deps
    - run: npm install
  
   
