name: testing
on: 
  workflow_dispatch:

jobs:
  start_back_end:
      runs-on: windows-latest
      defaults:
        run:
          working-directory: backend
      steps:
        - name: start the server
          uses: actions/checkout@v2
        - run: touch .env
        - run: echo MONGO_URI =${{ secrets.MONGO_URI }} >> .env
        - run: npm install
        - run: node server.js

  start_front_end:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: start the UI
        uses: actions/checkout@v2
      - run: npm install
      - run: npm start
      - run: npm run test-run

